/**
 * The embeddable entry point: `import { createConfigurator } from 'pg-configurator-web'`.
 *
 * The modules under `src/` mirror the Python reference file by file and are
 * reviewed that way; they are an implementation, not an interface. This file is
 * the interface, and it is deliberately narrow — everything here is covered by
 * the differential suite against the Python package, so it can be kept stable
 * across releases while the port underneath is free to follow its reference.
 *
 * Two ways to get the rule data in:
 *
 *   const pgc = await createConfigurator();            // Node: reads ./data
 *   const pgc = createConfigurator.withData({ rules, pgSettings });
 *
 * The second form takes no filesystem: a bundler or a browser imports the three
 * JSON payloads itself (they are published in this package under `web/data/`)
 * and passes them. Nothing in this module reads a file until `loadBundledData`
 * is actually called.
 */

import { createEnums } from './src/configurator.js';
import { makeConf, makeConfDefaults, getMajorVersion } from './src/make-conf.js';
import { PyValueError, sizeFrom, sizeTo, SYS_IEC, SYS_ISO, SYS_PG } from './src/units.js';

export { makeConf, makeConfDefaults, getMajorVersion };
export { PyValueError, sizeFrom, sizeTo, SYS_IEC, SYS_ISO, SYS_PG };

/** The PostgreSQL majors this build carries rules and settings snapshots for. */
export const SUPPORTED_MAJORS = Object.freeze([
  '9.6',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
]);

/**
 * Read the three bundled JSON payloads from disk. Node only.
 *
 * The imports are dynamic so that a browser bundle which passes its own data
 * never pulls `node:fs` in behind the caller's back.
 */
export async function loadBundledData() {
  const [{ readFileSync }, { fileURLToPath }, { dirname, join }] = await Promise.all([
    import('node:fs'),
    import('node:url'),
    import('node:path'),
  ]);
  const directory = join(dirname(fileURLToPath(import.meta.url)), 'data');
  const read = (name) => JSON.parse(readFileSync(join(directory, name), 'utf8')).payload;
  return { rules: read('rules.json'), pgSettings: read('pg_settings.json') };
}

/**
 * Bind the rule data once and generate configurations from it.
 *
 * `inputs` uses the `make_conf` parameter names, which are also the names in
 * the `pg_configurator/input-v1` JSON document and, with dashes, the long
 * options of the CLI. `cpu_cores` and `ram_value` are required; everything else
 * falls back to `makeConfDefaults()`.
 */
export function configuratorFromData({ rules, pgSettings }) {
  if (!rules || !pgSettings) {
    throw new PyValueError('createConfigurator requires both rules and pgSettings');
  }
  // The enum classes are derived once: they carry identity comparisons the
  // calculation relies on, so every run has to see the same objects.
  const data = { rules, pgSettings, enums: createEnums(rules.enums) };
  return {
    supportedMajors: SUPPORTED_MAJORS,
    defaults: makeConfDefaults(),
    generate(inputs = {}) {
      const { cpu_cores: cpuCores, ram_value: ramValue, ...options } = inputs;
      if (cpuCores === undefined || ramValue === undefined) {
        throw new PyValueError('inputs must include cpu_cores and ram_value');
      }
      return makeConf(cpuCores, ramValue, options, data);
    },
  };
}

/** `configuratorFromData` with the bundled payloads loaded for you. Node only. */
export async function createConfigurator(data = null) {
  return configuratorFromData(data ?? (await loadBundledData()));
}

/**
 * The `postgresql.conf` text, byte-for-byte what the reference CLI writes.
 *
 * `host` and `version` are parameters rather than looked up here: a library has
 * no business reading the hostname, and the CLI parity suite compares this
 * output with Python's for the machine both are running on.
 */
export function renderConf(result, { version, host }) {
  const lines = [
    `# Generated by pg-configurator ${version}`,
    `# PostgreSQL ${result.inputs.pg_version}; host ${host}`,
  ];
  for (const item of result.advisories) {
    const messageLines = String(item.message).split(/\r\n|[\r\n]/);
    lines.push(`# ${item.severity.toUpperCase()}: ${messageLines[0]}`);
    for (const line of messageLines.slice(1)) lines.push(`# ${line}`);
  }
  lines.push('');
  for (const [name, value] of Object.entries(result.config)) lines.push(`${name} = ${value}`);
  return `${lines.join('\n')}\n`;
}
